#+TITLE: Ruby Khipu
#+AUTHOR: Grant Shangreaux

* Introduction

A Ruby investigation and implementation of the data structure proposed based on the Inka [[https://www.khipufieldguide.com/guidebook/Introduction.html][Khipu]] that is proposed in the following paper:

[[https://ccsenet.org/journal/index.php/cis/article/view/0/52950][Quipu Data Structure]] by Richard Dosselmann, Edward Doolittle, Vatika Tayal

** What is a Khipu?

The Inkan civilization and people of the central Andes recorded information by tying knots into cords of woven threads. Most of what has been deciphered is numeric information. The knots are tied on cords in a way to represent a base 10 system. One type of knot encodes each digit 1-9, while the absence of a knot is zero. Position on a cord encodes units, tens, hundreds and so on. In addition, khipu knots have variations that make them easier to read, or encode additional information as signs.

#+begin_quote
Since the ones position on quipu cords are shown in a distinctive way (i.e., using long knots and figure-eight knots), it is usually clear where a number ends. Thus, it is possible that a single quipu cord could contain several numbers.[fn:1]
#+end_quote

Not all types of information Khipus encode has been deciphered. Cords come in different colors and weaving styles. Groups of cords are organized together, and some have a single cord tied off the top in a different direction.

** A Cord of Knots is an Integer

In the most basic interpretation, we read the combined knots of a cord as an integer.

For example, say we use dashes (~---~) for the cord, then symbols to
represent knots, which in turn represent a numeral:

1 → ●

4 → ⁛

5 → ⸭

Then this cord: ~--●--⸭-----⁛--~ is the integer 1,504.

What matters in this interpretation are the POSITION of the knot and the VALUE of the knot as a number. Because POSITION is relevant, we know that the numeral 4 (⁛) is in the units place, there's an implied zero in the tens, 5 (⸭) in the hundreds place, and 1 (●) in the thousands.

~--1--5--0--4--~
~--●--⸭-----⁛--~

Each cord encodes an integer, with each knot being a base 10 digit.[fn:3]

** Strands of Information

The Khipu is an information dense object meant for human interpretation. Khipu specialists called "khipu-kamayuq", maker-of-knots, encoded structured and narrative meaning into the woven cords. There was a spiritual connection cloth as a sacred object, and more meaning was added by the knot-makers. We will focus on interpreting them as numbers, but the khipu-kamayuq certainly had more ways of reading the knots. Even with only numbers, khipu were powerful ways of storing and communicating information.

#+begin_quote
I think of khipu as an ancient form of “spreadsheet”, made from woven cord. That’s an intentional metaphor - a spreadsheet both calculates (expected) and communicates (unexpected). Most modern khipu scholars agree that khipus serve both purposes, but beyond that, much disagreement exists. Our ability to “read” a khipu has been lost, and khipus remain one of the few remaining ancient communication mediums that remain enigmatic...[fn:2]
#+end_quote

Computer data structures are similar, but built for binary machine interpretation first. An integer is stored in memory as a series of zeroes and ones. 11000000111001 in binary is 12345 in base 10. It is more efficient for humans to use 10 as a base to encode integers, but a computer simply can't. Every bit of data is made up of only ones and zeroes. The amazing part is how almost anything we can think of is encoded in binary. If a stranger from the future found a string of ones-and-zeroes, would the ability to read the encoded information be lost as well?

** Weaving and Tangling

Transforming the cloth Khipu, cords woven and knotted by hand, into a computer data structure feels like an interesting space between present, past, and future. So much of my mind is occupied by computer languages and data modeling. As an indigenous American, the opportunity to weave indigenous knowledge and ways of communication into my world is a welcome thing.

This document is written as a [[https://en.wikipedia.org/wiki/Literate_programming#bodyContent][literate program.]] The code blocks encountered here are the source for the Ruby code files present in the repository. It is a happy coincidence that my favorite way to write is with [[https://orgmode.org/][Org mode for GNU Emacs]]. It allows us to *tangle* out the source code woven into the document. The tree structure of an org-mode document is heirarchical and grouped like Khipu. Working with programs this way helps see and understand information in new ways.

* Implementation

We'll start by implementing my understanding of khipu as an organized system of integer data. The paper says a khipu is "hierarchical, partially unsorted, grouped and summed". It is a tree structure(hierarchical) that allows arbitrary insertion (partially unsorted). Elements of the tree can be grouped, and groups have a built in summation via the "top-cord" feature.

If you aren't a programmer, don't worry. I hope that the physical example of the khipu will stay in your mind as we explore how Ruby encodes information in text. The code examples will avoid complexity and illustrate some fundamental parts of thinking with a computer language. If you're curious to know more, [[./ruby.org]] holds my thoughts on understanding it better.

** A Cord Made of String

To hold to our metaphor, we could use a Ruby object called a ~String~ to make a representation of a Cord.

#+begin_quote
A String object has an arbitrary sequence of bytes, typically representing text or binary data.
#+end_quote

Everything in Ruby is an ~Object~, and everything computers work with are made of bytes, which are a collection of bits; either ~0~ or ~1~. The type and direction of a Knot encodes numeric (and/or other) information on a Cord. A ~String~ carries ~character encoding~ which maps a sequence of 8-bit bytes (e.g ~01000011~) to "characters" in a specific set. The most common one in early computing was ~ASCII~, which maps bytes to the English alphabet, numbers, and symbols. These days, ~UTF-8~ is a more common encoding, its what allows things like emoji to be encoded 💾. Here's an example:

#+begin_src ruby :results code :exports both
  string = String.new("Khipu!")
  [string,
   string.encoding,
   string.bytes]
#+end_src

#+RESULTS:
#+begin_src ruby
["Khipu!", #<Encoding:UTF-8>, [75, 104, 105, 112, 117, 33]]
#+end_src

Ruby generally shows us a ~String~ literally, surrounded by quotes. The second bit shows sending the /message/ ~encoding~ to the ~string~ object. It /returns/ an ~Encoding~ object that tells us its a UTF-8 encoded string. The last part sends the ~bytes~ message which returns a list (or ~Array~) of numbers. In some ways, this is literally like a khipu's knotted cord. There's several layers of information encoding happening.

*** Building a Cord from a String

Let's build a string for the number 123. Like the example above I will use ~-~ dash characters to stand for an empty place on the cord. Ruby even lets us send the message ~to_i~ to a ~String~ to turn it into an ~Integer~. First build the empty cord, and demonstrate its integer value is zero:

#+begin_src ruby :exports both
  cord = "---"
  cord.to_i
#+end_src

#+RESULTS:
: 0

Next we want to set the units place to 3. We can interact with a /slice/ of a string using the "index operator" ~[]~. Counting up from ~0~ each slice of the string can be interacted with individually. Here's setting the units place to 3:

#+begin_src ruby :exports both
  cord = "---"
  cord[2] = 3.to_s
  cord
#+end_src

#+RESULTS:
: --3

#+begin_src ruby :exports both
  cord = "---"
  cord[2] = 3.to_s # set the units
  cord[1] = 2.to_s # set the tens
  cord[0] = 1.to_s # set the hundreds
  cord
#+end_src

#+RESULTS:
: 123

So far so good, but if we want to actually use this data for operations beyond just storing information, more work is needed. Strings can be added together, but it doesn't behave in a way that would work for any accounting:

#+begin_src ruby :exports both
  "123" + "321"
#+end_src

#+RESULTS:
: 123321

*** One More Step on this False Start

Ruby has many ways to express data and behavior. One way to allow ~String~ objects to act like Khipu Cords is to define a new /message/ strings can respond to. We call this "define ~method~ for objects of type ~Class~". So we will ~refine~ the ~String~ class with a new ~method~ called ~add_cord~. Then all string objects will know how to respond to receiving the ~add_cord~ message.

#+begin_src ruby :exports both
  module Khipu
    refine String do
      def add_cord(other)
        result = self.to_i + other.to_i
        result.to_s
      end
    end
  end

  using Khipu

  cord1 = "123"
  cord1.add_cord("321")
#+end_src

#+RESULTS:
: 444

This shows that we are able to define behavior on Ruby objects to express both Khipu as a heirarchical, partially sorted, grouped and summed data storage object, and a living object that has behavior for changing and interpreting it.

Changing the behavior of ~String~ objects in Ruby would be one way to do this, but we will define new Khipu-specific objects modeling their nature.

** Knots are Compound Data

The smallest unit of a Khipu is a ~Knot~.

Knots are like bytes, in that they could represent different kinds of information. For the initial example, we assume that a khipu is composed of groups of cords where each knot is of the same type. In our case, it is Integers, but a Knot could be anything really. Perhaps the color of the Cord tells you how to interpret the knots in a cord. Practically, keeping the elements of a Cord as Integers, but allowing arbitrarily high numbers would work like a primary key pointer to some other data structure. This would screw up the methods for adding things together.

However, see:

https://nithinbekal.com/posts/numeric-operations-value-objects/

#+name: Knot
#+begin_src ruby :results none
  Knot = Data.define(:digit, :spin) do
    @digits = Set.new(0..9).freeze
    @spins = Set.new(%i[s z u]).freeze
    def self.digits = @digits
    def self.spins = @spins

    def self.[](...) = new(...)
    def self.s_spin(digit) = new(digit:, spin: :s)
    def self.z_spin(digit) = new(digit:, spin: :z)

    def initialize(digit:, spin: :u)
      digit = Integer(digit)
      spin = spin.to_sym
      validate(digit, spin)

      super(digit:, spin:)
    end

    def inspect = "#{self.class}<#{digit}:#{spin}>"

    private

    def validate(digit, spin)
      validate_digit(digit)
      validate_spin(spin)
    end

    def validate_digit(digit)
      return if Knot.digits.include?(digit)

      raise(ArgumentError, "Knots can only be digits from 0-9.")
    end

    def validate_spin(spin)
      return if Knot.spins.include?(spin.to_sym)

      raise(ArgumentError, "Spins must be s, z, or u.")
    end
  end

  class Long < Knot; end
  class Figure8 < Knot; end
#+end_src

#+begin_src ruby :results output :noweb yes
  <<Knot>>

  error = begin
            Knot[10]
          rescue ArgumentError => e
            e
          end

  error2 = begin
             Knot[digit: 1, spin: :crazy]
           rescue ArgumentError => e
             e
           end

  pp [
    [Knot[1]],
    [Knot[digit: 2, spin: :z]],
    [Long.s_spin(3)],
    [Figure8.z_spin(4)],
    [error],
    [error2]
  ]
 #+end_src

 #+RESULTS:
 : [[#<data Knot digit=1, spin=:u>],
 :  [#<data Knot digit=2, spin=:z>],
 :  [#<data Long digit=3, spin=:s>],
 :  [#<data Figure8 digit=4, spin=:z>],
 :  [#<ArgumentError: Knots can only be digits from 0-9.>],
 :  [#<ArgumentError: Spins must be s, z, or u.>]]

** Strand base class

The paper's interface proposes a base class that is an iterable.

#+begin_src ruby :tangle yes
  class Strand
    attr_accessor :knots

    def initialize
      @knots = []
      @group = false
      @colour = nil
      @direction = false
    end

    def each(&block) = knots.each(&block)
    def <<(val) = knots << val
    def length = count
    def insert(i, x) = knots[i] = x
    def append(item) = knots.append(item)
    def concat(strand) = strand.each { |item| append(item) }
    def clear = knots.clear
    def copy = Marshal.load(Marshal.dump(self))

    # TODO
    def decrypt(key) = nil
    def encrypt = nil

    def to_s
      "#{group ? 1 : ''}|#{colour}|#{direction ? 1 : ''}|#{knots.join}"
    end

    private

    attr_reader   :group,
                  :colour,
                  :direction
  end
#+end_src

** Cord

#+begin_src ruby :tangle yes
  class Cord < Strand
    def colour=(rgba_array)
      @colour = Colour.new(*rgba_array)
    end

    def direction=(bool)
      @direction = bool
    end

    def +(cord)
      new_value = to_i + cord.to_i
      @knots = new_value.to_s.chars.map(&:to_i)
      self
    end

    def to_i = knots.join.to_i

    class Colour
      def initialize(r,g,b,a)
        @colour = [r,g,b,a]
      end

      def red = @colour[0]
      def green = @colour[1]
      def blue = @colour[2]
      def alpha = @colour[3]

      def to_s = "(#{red}, #{green}, #{blue}, #{alpha})"
    end
  end
#+end_src

** Group

#+begin_src ruby :tangle yes
  class Group < Strand
    attr_reader :top_cord

    def initialize(has_top = true)
      super()
      @group = true
      @has_top = has_top
      @top_cord = Cord.new if has_top?
    end

    def has_top? = !!@has_top

    def add_to_top_cord(cord)
      if has_top?
        @top_cord += cord
      else
        @top_cord = Cord.new
        @has_top = true
        @top_cord += cord
      end
    end

    def append(cord, top_cord = true)
      @knots << cord

      add_to_top_cord(cord) if top_cord
    end

    def to_s = ["1|||", @top_cord, knots].join("\n  ")

    def to_i
      return top_cord.to_i if has_top?

      knots.map(&:to_i).sum
    end

    def clear
      knots.clear
      @top_cord = Cord.new
      self
    end

    def concat(cords, update_top_cord = true)
      cords.each { |cord|
        add_to_top_cord(cord) if update_top_cord && has_top?
        knots << cord
      }
    end

    def insert(i, cord, top_cord = true)
      knots[i] = cord

      add_to_top_cord(cord) if top_cord
    end
  end
#+end_src

** Khipu

#+begin_src ruby :tangle yes
  class Khipu < Strand
    def to_s = knots.join("\n")

    # TODO
    def deserialize(path)
      File.readlines(path).each do |line|
        parts = line.split
        case parts
        in ["1", *]
          knots << Group.new
        in ["", String, *, String]
        end
      end
    end

    def new_cord = Cord.new
    def new_group = Group.new
    def serialize(path, indent=4, spaces=0) = nil
  end
#+end_src

* Notes
** Optimizing Cord to Integer

#+begin_src ruby :results output :exports both
  @knots = [1,2,3,4,5,6,7,8,9,0]

  def coercion
    @knots.join.to_i
  end

  def functional
    @knots.reduce(0) { |memo, i| memo * 10 + i }
  end

  def imperative_each
    result = 0
    @knots.each do |i|
      result = result * 10 + i
    end
    result
  end

  def imperative_while
    result = 0
    i = 0
    len = @knots.length
    while i < len
      result = result * 10 + @knots[i]
      i += 1
    end
    result
  end

  require 'benchmark'

  n = 1_000_000

  Benchmark.bm do |x|
    x.report("coercion:") { n.times { coercion } }
    x.report("functional") { n.times { functional } }
    x.report("imperative_each:") { n.times { imperative_each } }
    x.report("imperative_while:") { n.times { imperative_while } }
  end
#+end_src

#+RESULTS:
:                        user     system      total        real
: coercion:          0.766777   0.003551   0.770328 (  0.770378)
: functional         0.350813   0.001270   0.352083 (  0.352157)
: imperative_each:   0.266080   0.000249   0.266329 (  0.266360)
: imperative_while:  0.257264   0.000087   0.257351 (  0.257376)

** COMMENT Create a Knot Abstraction?

Knots are like bytes, in that they could represent different kinds of information.
For the initial example, we assume that a khipu is composed of groups of cords where
each knot is of the same type. In our case, it is Integers, but a Knot could be
anything really. Perhaps the color of the Cord tells you how to interpret the knots
in a cord. Practically, keeping the elements of a Cord as Integers, but allowing
arbitrarily high numbers would work like a primary key pointer to some other
data structure. This would screw up the methods for adding things together.

However, see:

https://nithinbekal.com/posts/numeric-operations-value-objects/

#+begin_src ruby :session knots :exports both, :results none
  Knot = Data.define(:digit, :spin) do
    @digits = Set.new(0..9).freeze
    @spins = Set.new(%i[s z u]).freeze
    def self.digits = @digits
    def self.spins = @spins

    def self.[](...) = new(...)
    def self.s_spin(digit) = new(digit:, spin: :s)
    def self.z_spin(digit) = new(digit:, spin: :z)

    def initialize(digit:, spin: :u)
      digit = Integer(digit)
      spin = spin.to_sym
      validate(digit, spin)

      super(digit:, spin:)
    end

    def inspect = "#{self.class}<#{digit}:#{spin}>"

    private

    def validate(digit, spin)
      validate_digit(digit)
      validate_spin(spin)
    end

    def validate_digit(digit)
      return if Knot.digits.include?(digit)

      raise(ArgumentError, "Knots can only be digits from 0-9.")
    end

    def validate_spin(spin)
      return if Knot.spins.include?(spin.to_sym)

      raise(ArgumentError, "Spins must be s, z, or u.")
    end
  end

  class Long < Knot; end
  class Figure8 < Knot; end
#+end_src

#+begin_src ruby :session knots :results value
  error = begin
            Knot[10]
          rescue ArgumentError => e
            e
          end

  error2 = begin
             Knot[digit: 1, spin: :crazy]
           rescue ArgumentError => e
             e
           end

  [
    [Knot[1]],
    [Knot[digit: 2, spin: :z]],
    [Knot.s_spin(3)],
    [Knot.z_spin(4)],
    [error],
    [error2]
  ]
 #+end_src

 #+RESULTS:
 : '((Knot<1:u>)  (Knot<2:z>)  (Knot<3:s>)  (Knot<4:z>)  (#<ArgumentError: Knots can only be digits from 0-9.>)  (#<ArgumentError: Spins must be s  z  or u.>))


*** COMMENT Knot with arithmetic operators and #coerce

This doesn't make sense for a Knot currently, they dont represent full
Numerics, only the base 10 digit symbols.

#+begin_src ruby :session knots_draft_1
  Knot = Data.define(:digit) do
    DIGITS = Set.new(0..9).freeze

    def initialize(digit:)
      digit = Integer(digit)
      raise(ArgumentError, "Must be digit 0-9.") unless DIGITS.include?(digit)

      super(digit:)
    end

    def +(other)
      wrap(other).then { |wrapped| Knot[digit + wrapped.digit] }
    end

    def -(other)
      wrap(other).then { |wrapped| Knot[digit - wrapped.digit] }
    end

    def *(other)
      wrap(other).then { |wrapped| Knot[digit * wrapped.digit] }
    end

    def /(other)
      wrap(other).then { |wrapped| Knot[digit / wrapped.digit] }
    end

    def **(n) = Knot[digit**n]
    def -@ = self * -1

    def coerce(n) = [Knot[n], self]
    def inspect = "Knot(#{digit})"

    private

    def wrap(value) = value.is_a?(Knot) ? value : Knot[value]
  end

  [[Knot[1]], [Knot[2]]]
#+end_src

#+RESULTS:
| Knot | (1) |
| Knot | (2) |


** Reference
*** Python Interface from the paper
#+begin_src python
  # 2.2.1 Class base
  # The interface of base (Base in Python) is given as follows.
  class Base:
  def __init__(self) ...
  def __iter__(self) ...
  def __len__(self) ...
  def __next__(self) ...
  def append(self, x) ...
  def clear(self) ...
  def copy(self) ...
  def decrypt(self, key) ...
  def encrypt(self, key) ...
  def extend(self, iterable) ...
  def insert(self, i, x) ...

  # 2.2.2 Class cord
  # The interface of cord (Cord) is given as follows.
  class Cord(Base):
  def __init__(self, colour_=None, direction_=False) ...
  def __add__(self, cord) ...
  @property
  def colour(self) ...
  @colour.setter
  def colour(self, colour_) ...
  def copy(self) ...
  @property
  def direction(self) ...
  @direction.setter
  def direction(self, direction_) ...
  def val(self) ...

  # 2.2.3 Class group
  # The interface of group (Group) is given as follows.
  class Group(Base):
  def __init__(self, top_cord_=True) ...
  def add_to_top_cord(self, cord) ...
  def append(self, cord, top_cord_=True) ...
  def clear(self) ...
  def copy(self) ...
  # http://cis.ccsenet.org Computer and Information Science Vol. 19, No. 1; 2026 56
  def extend(self, cords, top_cord_=True) ...
  def insert(self, i, cord, top_cord_=True) ...
  @property
  def top_cord(self) ...
  @top_cord.setter
  def top_cord(self, top_cord_) ...

  # 2.2.4 Class quipu
  # The interface of quipu (Quipu) is given as follows.
  class Quipu(Base):
  def __init__(self) ...
  def copy(self) ...
  def deserialize(self, path) ...
  def new_cord(self) ...
  def new_group(self) ...
  def serialize(self, path, indent=4, spaces=0
#+end_src
*** Ruby Numeric#coerce

The Numeric types in ruby use the ~coerce~ protocol to handle math operations
between different types of numbers. Following this protocol with the numerical
Cord objects may allow transparent arithmetic between Cords and core Ruby
Numeric types.

#+begin_example
call-seq:
coerce(other) -> array

Returns a 2-element array containing two numeric elements,
formed from the two operands +self+ and +other+,
of a common compatible type.

Of the Core and Standard Library classes,
Integer, Rational, and Complex use this implementation.

Examples:

i = 2 # => 2
i.coerce(3) # => [3, 2]
i.coerce(3.0) # => [3.0, 2.0]
i.coerce(Rational(1, 2)) # => [0.5, 2.0]
i.coerce(Complex(3, 4)) # Raises RangeError.

r = Rational(5, 2) # => (5/2)
r.coerce(2) # => [(2/1), (5/2)]
r.coerce(2.0) # => [2.0, 2.5]
r.coerce(Rational(2, 3)) # => [(2/3), (5/2)]
r.coerce(Complex(3, 4)) # => [(3+4i), ((5/2)+0i)]

c = Complex(2, 3) # => (2+3i)
c.coerce(2) # => [(2+0i), (2+3i)]
c.coerce(2.0) # => [(2.0+0i), (2+3i)]
c.coerce(Rational(1, 2)) # => [((1/2)+0i), (2+3i)]
c.coerce(Complex(3, 4)) # => [(3+4i), (2+3i)]

Raises an exception if any type conversion fails.
#+end

* Footnotes

[fn:1] https://en.wikipedia.org/wiki/Quipu
[fn:2] https://www.khipufieldguide.com/guidebook/Introduction.html
[fn:3] https://en.wikipedia.org/wiki/Decimal

